### ISSUE TITLE
Keg-cli: sync command fails when starting container

### ISSUE THREAD

**Issue by mpcarolin** [simpleviewinc/keg-hub#18]
When running a command like:
```bash
keg consumer start --sync evf
```
I encounter an error complaining that a `docker-compose.yml` file cannot be found:

<img width="826" alt="image" src="https://user-images.githubusercontent.com/9517356/92534734-6c4f5080-f1ea-11ea-9c82-980b9bb98ec2.png">

The workaround currently is to start the container, then sync through cli actions.

**Comment by lancetipton** [comment]
This is fixed in #42
